# Generated by Django 4.1.7 on 2023-05-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_genre_profile_pays_profile_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, upload_to='users/cover/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/profile/%Y/%m/%d/'),
        ),
    ]
