# Generated by Django 4.1.7 on 2023-05-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_post_user_name_alter_post_image_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
    ]
