# Generated by Django 4.1.7 on 2023-06-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_activity_other_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.TextField(blank=True, null=True),
        ),
    ]
